import{a as d,S as g,i as a}from"./assets/vendor-CYMld6vM.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const h="https://pixabay.com/api/",y="52318710-c8f94a6f7665a4ba5885a56a6";function b(o){const i={key:y,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0};return d.get(h,{params:i}).then(t=>(t.data.hits.length===0&&alert("Sorry, there are no images matching your search query. Please try again!"),t.data)).catch(t=>Promise.reject(t))}const u=document.querySelector(".gallery"),c=document.querySelector(".loader"),L=new g(".gallery a",{captionsData:"alt",captionDelay:250});function S(o){if(!Array.isArray(o)||o.length===0)return;const i=o.map(({webformatURL:t,largeImageURL:s,tags:e,likes:r,views:n,comments:p,downloads:m})=>`
<li class="gallery__item">
  <a class="gallery__link" href="${s}">
    <img class="gallery__image" src="${t}" alt="${e}" loading="lazy" />
  </a>
  <div class="info">
    <p class="info-item"><b>Likes</b> <span>${r}</span></p>
    <p class="info-item"><b>Views</b> <span>${n}</span></p>
    <p class="info-item"><b>Comments</b> <span>${p}</span></p>
    <p class="info-item"><b>Downloads</b> <span>${m}</span></p>
  </div>
</li>`).join("");u.insertAdjacentHTML("beforeend",i),L.refresh()}function E(){u.innerHTML=""}function q(){c&&c.classList.remove("is-hidden")}function l(){c&&c.classList.add("is-hidden")}const f=document.querySelector(".form"),w=f.querySelector('input[name="search-text"]');f.addEventListener("submit",P);function P(o){o.preventDefault();const i=w.value.trim();if(!i){a.warning({title:"Warning",message:"Please enter a search term.",position:"topRight"});return}q(),E(),b(i).then(t=>{const s=Array.isArray(t.hits)?t.hits:[];if(l(),!s.length){a.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}S(s),a.success({title:"Success",message:`Found ${s.length} images for "${i}".`,position:"topRight"})}).catch(t=>{l(),console.error("Error in main:",t),a.error({title:"Error",message:"Something went wrong while fetching images. Check console for details.",position:"topRight"})})}
//# sourceMappingURL=index.js.map
